language: php
php:
  - '7.2'
  - '7.3'


before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  - travis_retry composer install --no-progress --prefer-dist

script:
  - vendor/bin/phpcs --standard=./vendor/pd/coding-standard/src/PeckaCodingStandard/ruleset.xml --extensions=php src/
  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then vendor/bin/phpstan.phar analyse -l 7 src; fi

notifications:
  email: false
